name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-binaries:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: node20-linux-x64
            out: obsidian-mcp-optimike-linux
          - os: windows-latest
            target: node20-win-x64
            out: obsidian-mcp-optimike-win.exe
          - os: macos-latest
            target: node20-macos-x64
            out: obsidian-mcp-optimike-macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npx pkg dist/index.js --targets ${{ matrix.target }} --output ${{ matrix.out }}
      - run: shasum -a 256 ${{ matrix.out }} > ${{ matrix.out }}.sha256
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.out }}
          path: |
            ${{ matrix.out }}
            ${{ matrix.out }}.sha256

  npm-publish:
    needs: build-binaries
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
